### ISSUE TITLE
Local setup instructions

### ISSUE THREAD

**Issue by pained** [strudel-science/strudel-web#2]
For those of us who aren't used to working with React sites it's not clear how from the README instructions on how to get an environment for React/NPM setup in the first place.

Is it possible to provide a yaml file to create a Conda environment that'll setup stuff locally automagically?

Also the URL in the Git clone line needs to be updated to reflect the shift in org location.

**Comment by codytodonnell** [comment]
Fixed with https://github.com/strudel-science/strudel-web/commit/1be91f3d71cc0e73c66445b41e0b1a53806e71b2
