### ISSUE TITLE
Review Planning Framework - Overview page content

### ISSUE THREAD

**Issue by pained** [strudel-science/strudel-web#26]
Please review /planning-framework/overview content.

**Comment by pained** [comment]
Content should be available in main or the hotfix branch.

**Comment by sspoon** [comment]
The content seems fine, but the sentence in the three boxes below the bolded title seem to be at different levels, which made reading them a bit odd. Not sure if I'm describing that well

**Comment by pained** [comment]
Comments addressed via PR @ #42
