### ISSUE TITLE
Review Planning Framework - Typology page content

### ISSUE THREAD

**Issue by pained** [strudel-science/strudel-web#27]
Please review /planning-framework/typology content.

**Comment by pained** [comment]
Content should be available in main or the hotfix branch.

**Comment by sspoon** [comment]
The content seems fine, but the sentence in the three boxes below the bolded title seem to be at different levels, which made reading them a bit odd. Not sure if I'm describing that well

**Comment by sspoon** [comment]
I think the content overall looks good. The part I'm unsure of is that it says its to be usable by anyone, but there's really nothing about where or how to access it. I wonder if we need to put that this is active research or something like that

**Comment by dangunter** [comment]
The initial sentence "STRUDEL research and design developed a wide ranging sociotechnical typology to categorize aspects of scientific software development." is a little intimidating

**Comment by dangunter** [comment]
Typology dimensions image, the smallest text isn't very readable. Maybe that's a feature.

**Comment by pained** [comment]
@dangunter yes generally. Also waiting on @Rjdesh and @sspoon to update that image in Figma for me.

**Comment by pained** [comment]
Most comments addressed via PR @ #42
