### ISSUE TITLE
DS: Tutorial(s)

### ISSUE THREAD

**Issue by pained** [strudel-science/strudel-web#70]
Get the Getting Started Tutorial up on the website

https://strudel.science/design-system/tutorials/

**To Do**

Modules:
- [x] Intro (Cody)
- [x] Set Up Your Development Environment (Dan)
- [x] Build an App with STRUDEL (Dan)
- [x] Add a Task Flow to Your App (Dan)
- [x] Customize Your Task Flow (Cody)
- [x] Customize Your App (Cody)
- [x] Customize the Home Page (Cody)
- [x] Continue Learning (Cody)

Tasks:
- [x] Update tenses so they are all consistent
- [x] Add key concepts and terminology to intro
- [x] Add images
- [x] Remove TODO comments
- [x] Remove extra imports
- [x] Edit task flow template readmes so pip install step is correct

**Comment by codytodonnell** [comment]
**To Do**

Modules:
- [ ] Intro (Cody)
- [ ] Set Up Your Development Environment (Dan)
- [ ] Build an App with STRUDEL (Dan)
- [ ] Add a Task Flow to Your App (Dan)
- [ ] Customize Your Task Flow (Cody)
- [ ] Customize Your App (Cody)
- [ ] Continue Learning (Cody)

Tasks:
- [ ] Update tenses so they are all consistent
- [ ] Add key concepts and terminology to intro
